### ISSUE TITLE
Change movie table primary key to `imdb_id` instead of `title`

### ISSUE THREAD

**Issue by chrispinkney** [funnls/cinesync#5]
**Needs investigation** but I think a better single source of truth for the table could be the `imdb_id` instead of a title. Titles can change but I imagine `imdb_id`s are _for life_.

**Comment by manekenpix** [comment]
This was addressed in this commit https://github.com/funnls/cinesync/commit/8950141e78607d419a647d1d51ae1ec9978af2d0
